#!/usr/bin/env node

var path = require('path'),
    fs = require('fs'),
    program = require('commander'),
    pkg = require('../package.json'),
    index = require('../lib/index');

program
    .version(pkg.version)
    .option('-e, --verbose', 'log full info')
    .parse(process.argv);

index.main(process.argv[2], !program.verbose);

